### ISSUE TITLE
Configurable number of connections to memcached server

### ISSUE THREAD

**Issue by guptakeshav24** [spotify/folsom#106]
Currently in folsom number of connections are fixed. There should be a way to provide initial number of connections and max number of connections. Advantage of this feature is folsom will initially make some connections and then it will make more connections at runtime as and when required.

**Comment by spkrka** [comment]
There is already `MemcacheClientBuilder.withConnections()` you can use to explicitly control number of connections per host. The default value is 1.

You can start by trying to increase that and see if you get any performance improvement - I am not sure there's enough value in having it be more dynamic though - and if so, what would be the conditions for increasing or decreasing number of connections?

**Comment by spkrka** [comment]
Closing since it has not been updated in a while
