### ISSUE TITLE
let's add docs how to run build and tests locally? (Docker container)

### ISSUE THREAD

**Issue by alexeyOnGitHub** [spotify/folsom#132]
the build fails on my computer due to some configuration required for Docker container.:

> Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
> 
> java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration

if the build requires some initial setup on a local computer or a Jenkins node, let's add a short snippet about this to the docs?

**Comment by spkrka** [comment]
That's a good idea! I'll try to make that happen
