### ISSUE TITLE
Add Micrometer metrics

### ISSUE THREAD

**Issue by checketts** [spotify/folsom#185]
I noticed the project has Yammer Metrics a an option. Would you be interested in a [Micrometer](https://micrometer.io/) metrics contribution, following the yammer metrics pattern?

It is a metrics facade that allows many other backends (Prometheus in my case)

**Comment by protocol7** [comment]
Yeah, since getting metrics from Folsom is very useful, having more metrics integrations would make sense. We'd welcome a contribution for Micrometer.

**Comment by checketts** [comment]
This has been merged into master.

@protocol7 How often are releases created?

**Comment by checketts** [comment]
Its been a bit since #186 was merged in. Is there anything outstanding before a release can happen?
