### ISSUE TITLE
Introduce OpenTelemetry metrics and tracing

### ISSUE THREAD

**Issue by evg-tso** [spotify/folsom#222]
Hi,

I see that OpenTelemetry's metrics and tracing are missing in this repo.  
Since [OpenTracing and OpenCensus have been merged to form the OpenTelemetry project](https://opentelemetry.io/blog/2023/sunsetting-opencensus/), I wonder if we should add another Metrics/Tracer implementation for OpenTelemetry here, or somewhere in the [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation) project.

What do you think?  
If you think it's worthwhile, I can work on adding another implementation for OTEL metrics as a first step.

**Comment by protocol7** [comment]
Such a contribution would surely be welcomed :)

**Comment by korzepadawid** [comment]
Assign it to me :)

**Comment by thiagocesarj** [comment]
OpenTelemetry metrics now available thanks to @korzepadawid ! Closing the issue
