### ISSUE TITLE
Last 2 versions were not released

### ISSUE THREAD

**Issue by paralainer** [spotify/folsom#241]
1.18.0 and 1.19.0 were prepared for release but never actually released, 1.17.0 is the latest one on maven central. We'd like to use some features from latest releases, what is the plan with pushing new versions to repository?

**Comment by thiagocesarj** [comment]
@paralainer sorry for the delay, the build system was very stubborn in its desire to remain broken, but alas, it's healthy again. We were able to release a new version with your contributions - 1.20.0.
