### ISSUE TITLE
Maximum value size

### ISSUE THREAD

**Issue by spkrka** [spotify/folsom#34]
For set operations, should we do something special to respect maximum value size? Or should we just send it anyway and rely on the failure we get back?

**Comment by spkrka** [comment]
I think there may be a bug related to sending too large SET requests - it seems like the connection state itself can get corrupted and failing all subsequent requests with SERVER_ERROR

**Comment by danielnorberg** [comment]
Is this issue reproducible?

**Comment by spkrka** [comment]
I haven't tried yet, but I plan to attempt to reproduce it soon (hopefully with a unit test) unless someone beats me to it.

The fix should be simple - enforce a maximum value size.
