### ISSUE TITLE
Any idea to implement jsr 107?

### ISSUE THREAD

**Issue by linux-china** [spotify/folsom#49]
JSR 107 is a specification for java cache, and the site is https://github.com/jsr107.  Could your guys implement this jsr specification for convenient api usage?

**Comment by danielnorberg** [comment]
I believe JSR 107 might be outside the scope of folsom and seeing as it's currently missing e.g. async, we're unlikely to use JSR 107 ourselves. But a JSR 107 implementation could likely be built on top of folsom if desired.

**Comment by linux-china** [comment]
@danielnorberg  yes, you are right. JSR 107 will implement the async feature in its api.   An adapter for JSR 107 built on top folsom is a good idea, maybe folsom-jsr107.  I have implemented  JSR 107 feature for another memcached client, and I will take a look at the folsom's api and implement folsom-jsr107 adapter.

**Comment by spkrka** [comment]
I agree with @danielnorberg

JSR-107 is not important enough to put into core folsom, but someone else can of course create a wrapper project.

Some notes:
- Cache is Iterable, and iterating keys is not something that is supported by memcached.
- It does seem to have some async functionality (get with collector)
