### ISSUE TITLE
Target Java 8 and s/ListenableFuture/CompletableFuture/g EOM

### ISSUE THREAD

**Issue by danielnorberg** [spotify/folsom#54]

**Comment by spkrka** [comment]
:-1: Perhaps in the future when folsom has stabilized more and java8 is more widely adopted. I don't want to break java 7 support just quite yet.

Also, I am not sure I like CompletableFuture as much as ListenableFuture.
I agree with the list of shortcomings here: http://www.nurkiewicz.com/2013/05/java-8-completablefuture-in-action.html (except the second one, there is a CompletionStage interface)

**Comment by danielnorberg** [comment]
Yeah, didn't necessarily mean that we should do this asap, but rather just get a discussion going.

My guess is that in the future CompletableFuture usage is going to be quite wide-spread and people might not be pulling in guava as much to get ListenableFuture.

Guava can be a significant dependency burden for users as its releases are often not fully backwards compatible. We've seen breakage due to this in the past.

As such there could be value in not having a library such as folsom depend on guava. Especially if it's just to use an interface that in the future will be regarded as an anachronism.

But let's see what happens and revisit in 6 months or so.

**Comment by spkrka** [comment]
Agreed. This probably (with a strong probably) makes sense at some point in the future.

**Comment by flozano** [comment]
+1 on this (hate that github has no "vote"). In the meantime I will do a wrapper using https://github.com/lukas-krecan/future-converter

**Comment by spkrka** [comment]
This has been resolved
