### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by flozano** [spotify/folsom#59]
Hi there,

What is the status of this project? It looks great but it seems there's very low activity on it... do you plan to keep developing it, or is it in "bugfix" mode now? any roadmap?

**Comment by protocol7** [comment]
@flozano Folsom is heavily used within Spotify so in that sense we'll continue maintaining it, including adding whatever features we need. We of course also welcome external contributions. We don't have a roadmap of features that we're planning on adding, rather they happen on a as-needed basis.

**Comment by flozano** [comment]
Thanks for the feedback, that makes me more comfortable about using it seriously.

**Comment by spkrka** [comment]
@protocol7 is pretty much spot on. It is used heavily internally at Spotify, but we haven't had any problems lately and no one has requested any additional features so activity has been low.

I would be very happy to see some external contributions in the form of pull requests, feature requests or bug reports (or other types i haven't even considered)!
