### ISSUE TITLE
Support for 'flush_all'

### ISSUE THREAD

**Issue by flozano** [spotify/folsom#64]
It would be great if this command was supported.

**Comment by spkrka** [comment]
There is an existing pull request open for that: https://github.com/spotify/folsom/pull/26

I am not sure why we haven't merged that yet. Perhaps someone could investigate and rebase it at some point.

**Comment by flozano** [comment]
Any chance of this being revisited?

**Comment by spkrka** [comment]
Yes, I'll see when I have time to implement it.

**Comment by spkrka** [comment]
Fixed with #101 - will be released as 1.2.0
