### ISSUE TITLE
Fix validation of max key size to work with InnoDB Memcached

### ISSUE THREAD

**Issue by jludvice** [spotify/folsom#81]
Hi Folsom developers, 

could you please consider changing validation of max key length in folsom from 250 to 249?

Everything works fine with Memcached where their validation looks like this:
https://github.com/memcached/memcached/blob/master/memcached.c

```c
#define KEY_MAX_LENGTH 250

if(nkey > KEY_MAX_LENGTH) {
    out_string(c, "CLIENT_ERROR bad command line format");
    return;
}
```

But there is issue with MySQL InnoDB Memcached, where they are off by one.
https://github.com/mysql/mysql-server/blob/5.7/plugin/innodb_memcached/innodb_memcache/src/innodb_engine.c#L1462

```c
#define KEY_MAX_LENGTH	250

assert(*name_len < KEY_MAX_LENGTH);
```

They acutally allow max 249.
Our MySQL with this Memcached "frontend" actually went down due to high load and rate it was throwing errors on too big key length.

**Comment by jludvice** [comment]
This should be resolved by #83, right @protocol7 ?
Do you plan to cut new release any time soon?

**Comment by protocol7** [comment]
@jludvice Yeah, this should be solved by #83, could you verify that that is the case for you and we'll push a release :)

**Comment by jludvice** [comment]
Thank you @protocol7. I think it's fine for us, but let me please double check and confirm next week.
Have a nice weekend :)

**Comment by jludvice** [comment]
Hi @protocol7, just verified that #83 worked fine. 

+1 for resolving this issue
