### ISSUE TITLE
Client failure after responding to too many requests where value is too large

### ISSUE THREAD

**Issue by morrifeldman** [spotify/folsom#91]
I ran into an issue in production where we started getting `MemcacheOverloadedException`s and the client was never able to reconnect.  In our use case we are perhaps abusing the client with 1 to 2 requests per minute to cache values that are too large and after a few days the client crashes.  I think I've tracked the problem to the code [here](https://github.com/spotify/folsom/blob/master/folsom/src/main/java/com/spotify/folsom/client/DefaultRawMemcacheClient.java#L216). When responding for a `VALUE_TO_LARGE` the pendingCounter is not decremented.  Looking at the outstandingRequests metric, I can see this counter get incremented for every request to cache a too large value.  Once the pending requests counter reaches the specified outstanding request limit (default 1000) the client fails and the application must be restarted.

The fix looks straight forward and I'll be happy to submit a pull request if you'd like.

**Comment by spkrka** [comment]
Thanks for the report and PR! We'll merge either that one or #93 soon.

**Comment by spkrka** [comment]
Should be fixed in release 1.1.1 now.
